services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: sam
        uid: 1000
    image: tejarat-laravel-app
    container_name: tejarat-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tejarat-network

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: tejarat-laravel-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - tejarat-network

# Docker Networks
networks:
  tejarat-network:
    driver: bridge
